#!/usr/bin/env bash
cd tests

echo 'testing awk'
../../cli/execute awk test.awk
echo 'testing c'
../../cli/execute c test.c
echo 'testing cpp'
../../cli/execute cpp test.cpp
echo 'testing cs'
../../cli/execute cs test.cs
echo 'testing deno'
../../cli/execute deno testdeno.ts
echo 'testing elisp'
../../cli/execute elisp test.el
echo 'testing elixir'
../../cli/execute exs test.exs
echo 'testing go'
../../cli/execute go test.go
echo 'testing haskell'
../../cli/execute haskell test.hs
echo 'testing java'
../../cli/execute java test.java
echo 'testing jelly'
../../cli/execute jelly test.jelly
echo 'testing jl'
../../cli/execute jl test.jl
echo 'testing js'
../../cli/execute js test.js
echo 'testing kotlin'
../../cli/execute kotlin test.kt
echo 'testing asm 32 bit'
../../cli/execute asm test.nasm
echo 'testing asm 64 bit'
../../cli/execute asm64 test64.nasm
echo 'testing php'
../../cli/execute php test.php
echo 'testing perl'
../../cli/execute perl test.pl
echo 'testing ruby'
../../cli/execute ruby test.rb
echo 'testing rust'
../../cli/execute rust test.rs
echo 'testing bash'
../../cli/execute bash test.sh
echo 'testing swift'
../../cli/execute swift test.swift
echo 'testing typescript'
../../cli/execute typescript test.ts
echo 'testing python2'
../../cli/execute python2 test2.py
echo 'testing python3'
../../cli/execute python3.8 test3.py
echo 'testing paradoc'
../../cli/execute bash test_paradoc.sh
