#!/usr/bin/env bash
cd tests

echo 'testing awk'
../execute awk test.awk
echo 'testing c'
../execute c test.c
echo 'testing cpp'
../execute cpp test.cpp
echo 'testing cs'
../execute cs test.cs
echo 'testing deno'
../execute deno testdeno.ts
echo 'testing elisp'
../execute elisp test.el
echo 'testing elixir'
../execute exs test.exs
echo 'testing go'
../execute go test.go
echo 'testing haskell'
../execute haskell test.hs
echo 'testing java'
../execute java test.java
echo 'testing jelly'
../execute jelly test.jelly
echo 'testing jl'
../execute jl test.jl
echo 'testing js'
../execute js test.js
echo 'testing kotlin'
../execute kotlin test.kt
echo 'testing asm 32 bit'
../execute asm test.nasm
echo 'testing asm 64 bit'
../execute asm64 test64.nasm
echo 'testing php'
../execute php test.php
echo 'testing perl'
../execute perl test.pl
echo 'testing ruby'
../execute ruby test.rb
echo 'testing rust'
../execute rust test.rs
echo 'testing bash'
../execute bash test.sh
echo 'testing swift'
../execute swift test.swift
echo 'testing typescript'
../execute typescript test.ts
echo 'testing python2'
../execute python2 test2.py
echo 'testing python3'
../execute python3 test3.py
echo 'testing paradoc'
../execute python3 test_paradoc.py
