#!/usr/bin/env bash
cd tests

echo 'testing awk'
../../cli/execute awk awk.awk
echo 'testing bash'
../../cli/execute bash bash.sh
echo 'testing c'
../../cli/execute c c.c
echo 'testing cpp'
../../cli/execute cpp cpp.cpp
echo 'testing csharp'
../../cli/execute csharp csharp.cs
echo 'testing deno'
../../cli/execute deno deno.ts
echo 'testing elixir'
../../cli/execute elixir elixir.exs
echo 'testing emacs'
../../cli/execute emacs emacs.el
echo 'testing go'
../../cli/execute go go.go
echo 'testing haskell'
../../cli/execute haskell haskell.hs
echo 'testing java'
../../cli/execute java java.java
echo 'testing jelly'
../../cli/execute jelly jelly.jelly good
echo 'testing julia'
../../cli/execute julia julia.jl
echo 'testing kotlin'
../../cli/execute kotlin kotlin.kt
echo 'testing nasm 32 bit'
../../cli/execute nasm nasm.nasm
echo 'testing nasm 64 bit'
../../cli/execute nasm64 nasm64.nasm
echo 'testing node'
../../cli/execute node node.js
echo 'testing paradoc'
../../cli/execute bash paradoc.sh
echo 'testing perl'
../../cli/execute perl perl.pl
echo 'testing php'
../../cli/execute php php.php
echo 'testing python2'
../../cli/execute python2 python2.py
echo 'testing python3'
../../cli/execute python3 python3.py
echo 'testing ruby'
../../cli/execute ruby ruby.rb
echo 'testing rust'
../../cli/execute rust rust.rs
echo 'testing swift'
../../cli/execute swift swift.swift
echo 'testing typescript'
../../cli/execute typescript typescript.ts
