#!/usr/bin/env bash
echo '---'
echo 'awk'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "awk -W version"
echo '---'
echo 'bash'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "bash --version"
echo '---'
echo 'c'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "gcc -v"
echo '---'
echo 'cpp'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "g++ -v"
echo '---'
echo 'csharp'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "mcs --version"
echo '---'
echo 'go'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "go version"
echo '---'
echo 'java'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "java -version"
echo '---'
echo 'nasm'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "nasm -version"
echo '---'
echo 'node'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "node --version"
echo '---'
echo 'php'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "php -v"
echo '---'
echo 'python2'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "python -V"
echo '---'
echo 'python3'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "python3 -V"
echo '---'
echo 'ruby'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "ruby --version"
echo '---'
echo 'rust'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "rustc --version"
echo '---'
echo 'swift'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "swift --version"
echo '---'
echo 'typescript'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "tsc --version"
echo '---'
