# This "FROM" image is previously emitted by nix
FROM ghcr.io/engineer-man/piston:base-latest

ENV PISTON_FLAKE_PATH=/piston/src
COPY runtimes/ /piston/src/runtimes
COPY flake.nix flake.lock /piston/src/


ARG RUNTIMESET=all
ENV PISTON_RUNTIME_SET=$RUNTIMESET

RUN piston-install
