#!/usr/bin/env bash

echo -n 'testing awk = '
../../cli/execute awk awk.awk
echo -n 'testing bash = '
../../cli/execute bash bash.sh
echo -n 'testing c = '
../../cli/execute c c.c
echo -n 'testing cpp = '
../../cli/execute cpp cpp.cpp
echo -n 'testing crystal = '
../../cli/execute crystal crystal.cr
echo -n 'testing csharp = '
../../cli/execute csharp csharp.cs
echo -n 'testing d = '
../../cli/execute d d.d
echo -n 'testing dash = '
../../cli/execute dash dash.sh
echo -n 'testing deno = '
../../cli/execute deno deno.ts
echo -n 'testing elixir = '
../../cli/execute elixir elixir.exs
echo -n 'testing emacs = '
../../cli/execute emacs emacs.el
echo -n 'testing go = '
../../cli/execute go go.go
echo -n 'testing haskell = '
../../cli/execute haskell haskell.hs
echo -n 'testing java = '
../../cli/execute java java.java
echo -n 'testing jelly = '
../../cli/execute jelly jelly.jelly good
echo -n 'testing julia = '
../../cli/execute julia julia.jl
echo -n 'testing kotlin = '
../../cli/execute kotlin kotlin.kt
echo -n 'testing lisp = '
../../cli/execute lisp lisp.cl
echo -n 'testing nasm 32 bit = '
../../cli/execute nasm nasm.nasm
echo -n 'testing nasm 64 bit = '
../../cli/execute nasm64 nasm64.nasm
echo -n 'testing nim = '
../../cli/execute nim nim.nim
echo -n 'testing node = '
../../cli/execute node node.js
echo -n 'testing osabie = '
../../cli/execute osabie osabie.abe
echo -n 'testing paradoc = '
../../cli/execute bash paradoc.sh
echo -n 'testing perl = '
../../cli/execute perl perl.pl
echo -n 'testing php = '
../../cli/execute php php.php
echo -n 'testing python2 = '
../../cli/execute python2 python2.py
echo -n 'testing python3 = '
../../cli/execute python3 python3.py
echo -n 'testing ruby = '
../../cli/execute ruby ruby.rb
echo -n 'testing rust = '
../../cli/execute rust rust.rs
echo -n 'testing scala = '
../../cli/execute scala scala.scala
echo -n 'testing swift = '
../../cli/execute swift swift.swift
echo -n 'testing typescript = '
../../cli/execute typescript typescript.ts
echo -n 'testing zig = '
../../cli/execute zig zig.zig
