#!/usr/bin/env bash
echo '---'

echo 'awk'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "awk -W version"
echo '---'

echo 'bash'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "bash --version"
echo '---'

echo 'brainfuck'
echo '1.0.0'
echo '---'

echo 'c'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "gcc --version"
echo '---'

echo 'cpp'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "g++ --version"
echo '---'

echo 'crystal'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "crystal -v"
echo '---'

echo 'csharp'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "mcs --version"
echo '---'

echo "elixir"
lxc-attach --clear-env -n piston -- /bin/bash -l -c "elixir --version"
echo '---'

echo 'd'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "dmd --version"
echo '---'

echo 'dash'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "dpkg -s dash"
echo '---'

echo 'deno'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "deno --version"
echo '---'

echo "emacs"
lxc-attach --clear-env -n piston -- /bin/bash -l -c "emacs --version"
echo '---'

echo 'go'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "go version"
echo '---'

echo 'haskell'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "ghc --version"
echo '---'

echo 'java'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "java -version"
echo '---'

echo 'jelly'
echo '1.0.0'
echo '---'

echo 'julia'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "julia --version"
echo '---'

echo 'kotlin'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "kotlinc -version 2>&1 | grep kotlin"
echo '---'

echo 'lisp'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "sbcl --version"
echo '---'

echo 'lua'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "lua -v"
echo '---'

echo 'nasm'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "nasm -version"
echo '---'

echo 'nasm64'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "nasm -version"
echo '---'

echo 'nim'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "nim -v"
echo '---'

echo 'node'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "node --version"
echo '---'

echo 'perl'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "perl --version | grep x86"
echo '---'

echo 'php'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "php -v"
echo '---'

echo 'python2'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "python -V"
echo '---'

echo 'python3'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "python3.8 -V"
echo '---'

echo 'paradoc'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "python3.8 -m paradoc --version"
echo '---'

echo 'ruby'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "ruby --version"
echo '---'

echo 'rust'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "rustc --version"
echo '---'

echo 'scala'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "scala -version"
echo '---'

echo 'swift'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "swift --version"
echo '---'

echo 'typescript'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "tsc --version"
echo '---'

echo 'zig'
lxc-attach --clear-env -n piston -- /bin/bash -l -c "zig version"
echo '---'

echo 'osabie'
echo '1.0.1'
echo '---'
