#!/bin/bash

cd /tmp/$1

sed 's/^.*$/:- forall((Goal = (\0), call(Goal)), (write(Goal), nl))./' stdin.stdin |
    cat code.code - > code.pl

if [ -s args.args ]
then
    echo ":- main($(jq --raw-input -c --slurp 'split("\n")' args.args))." >> code.pl
fi

timeout -s KILL 3 swipl -g true -t halt code.pl
