#!/bin/bash

runuser runner$1 -c "
    cd /tmp/$2
    mv code.code interim.ts
    tsc interim.ts
    rm -f interim.ts
    mv interim.js code.code
    xargs -a args.args -d '\n' timeout -s KILL 3 node code.code < stdin.stdin
"
