#!/usr/bin/env bash

systemctl start piston@1.service
systemctl start piston@2.service
systemctl start piston@3.service
systemctl start piston@4.service
systemctl start piston@5.service
systemctl start piston@6.service
systemctl start piston@7.service
systemctl start piston@8.service
systemctl start piston@9.service
systemctl start piston@10.service
systemctl start dock@1.service
systemctl start dock@2.service
systemctl start dock@3.service
systemctl start dock@4.service
systemctl start dock@5.service
systemctl start dock@6.service
systemctl start dock@7.service
systemctl start dock@8.service
systemctl start dock@9.service
systemctl start dock@10.service
