FROM debian:buster-slim AS python-package-builder

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's|http://deb.debian.org/debian-security|http://archive.debian.org/debian-security|g; s|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g; s|http://deb.debian.org/debian|http://archive.debian.org/debian|g; /buster-updates/d' /etc/apt/sources.list && \
    apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y unzip autoconf build-essential libssl-dev \
        pkg-config zlib1g-dev libargon2-dev libsodium-dev libcurl4-openssl-dev \
        sqlite3 libsqlite3-dev libonig-dev libxml2 libxml2-dev bc curl git \
        perl xz-utils python3 python3-pip gnupg jq zlib1g-dev \
        cmake cmake-doc extra-cmake-modules build-essential gcc binutils bash coreutils \
        util-linux pciutils usbutils coreutils binutils findutils grep libncurses5-dev \
        libncursesw5-dev python3-pip libgmp-dev libmpfr-dev python2 libffi-dev gfortran \
        libreadline-dev libblas-dev liblapack-dev libpcre3-dev libarpack2-dev libfftw3-dev \
        libglpk-dev libqhull-dev libqrupdate-dev libsuitesparse-dev libsundials-dev \
        libbz2-dev liblzma-dev libpcre2-dev gperf bison flex g++ gawk zip && \
        ln -sf /bin/bash /bin/sh && \
        rm -rf /var/lib/apt/lists/*

WORKDIR /piston/packages
COPY packages/Makefile /piston/packages/Makefile
COPY packages/python/3.13.0 /piston/packages/python/3.13.0

RUN make -j"$(nproc)" python-3.13.0.pkg.tar.gz PLATFORM=docker-debian

FROM buildpack-deps:bookworm AS isolate
RUN apt-get update && \
    apt-get install -y --no-install-recommends git libcap-dev && \
    rm -rf /var/lib/apt/lists/* && \
    git clone https://github.com/envicutor/isolate.git /tmp/isolate/ && \
    cd /tmp/isolate && \
    git checkout af6db68042c3aa0ded80787fbb78bc0846ea2114 && \
    make -j$(nproc) install && \
    rm -rf /tmp/*

FROM node:24-bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg-reconfigure -p critical dash
RUN apt-get update && \
    apt-get install -y libxml2 gnupg tar coreutils util-linux libc6-dev \
    binutils build-essential locales libpcre3-dev libevent-dev libgmp-dev \
    libncurses6 libncurses5 libedit-dev libseccomp-dev rename procps python3 \
    libreadline-dev libblas-dev liblapack-dev libpcre3-dev libarpack2-dev \
    libfftw3-dev libglpk-dev libqhull-dev libqrupdate-dev libsuitesparse-dev \
    libsundials-dev libpcre2-dev libcap-dev libssl-dev ca-certificates && \
    rm -rf /var/lib/apt/lists/*
RUN useradd -M piston
COPY --from=isolate /usr/local/bin/isolate /usr/local/bin
COPY --from=isolate /usr/local/etc/isolate /usr/local/etc/isolate

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

RUN mkdir -p /piston/packages/python/3.13.0
COPY --from=python-package-builder /piston/packages/python-3.13.0.pkg.tar.gz /tmp/python-3.13.0.pkg.tar.gz
RUN cd /piston/packages/python/3.13.0 && \
    tar xzf /tmp/python-3.13.0.pkg.tar.gz && \
    env -i bash -c 'cd /piston/packages/python/3.13.0; source environment; env' \
        | grep -v -E '^(PWD|OLDPWD|_|SHLVL)=' > .env && \
    date +%s > .ppman-installed && \
    rm /tmp/python-3.13.0.pkg.tar.gz

WORKDIR /piston_api
COPY api/package.json api/package-lock.json ./
RUN npm install
COPY api/src ./src

CMD ["/piston_api/src/docker-entrypoint.sh"]
EXPOSE 2000/tcp
